[package]
name = "{{project-name}}"
version = "0.1.0"

[lib]
kind = "tx-script"
namespace = "miden:base/transaction-script@1.0.0"

[dependencies]
# TODO: Add your account contract dependencies here
add-contract = { path = "../add-contract"}

[package.metadata.dependencies]
add-contract = { wit = "../add-contract/target/generated-wit/" }
