package miden:{{crate_name | replace: "_", "-"}}@0.1.0;

use miden:base/core-types@1.0.0;

interface {{crate_name | replace: "_", "-"}} {
    use core-types.{felt, asset};

    add: func(a: felt, b: felt) -> felt;

}

world {{crate_name | replace: "_", "-"}}-world {
    include miden:core-intrinsics/intrinsics@1.0.0;
    include miden:core-stdlib/stdlib@1.0.0;
    include miden:core-base/base@1.0.0;

    export {{crate_name | replace: "_", "-"}};
}
